### ISSUE TITLE
Error: path must be a string

### ISSUE THREAD

**Issue by konsumer** [JohnPostlethwait/stringify#15]
Sort of unhelpful error message. I am using it in package.json, like this:

```json
  "scripts": {
    "js": "browserify index.js -x ractive --standalone gauge -o dist/ractive-gauge.js && uglifyjs dist/ractive-gauge.js -o dist/ractive-gauge.min.js"
  },
  "browserify": {
    "transform": [
      "stringify", {
        "extensions": ".svg"
      }
    ]},
  "devDependencies": {
    "browserify": "^8.1.3",
    "stringify": "^3.1.0",
    "uglify-js": "^2.4.16"
  },
```

I get this error:

```
Error: path must be a string
    at .../ractive-gauge/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:16:16
    at process._tickCallback (node.js:355:11)
```

It works fine if I remove text-requires & the transform stuff.

**Comment by JohnPostlethwait** [comment]
That error is from Node Resolve: https://github.com/substack/node-resolve/blob/master/lib/async.js#L16

I'm not sure offhand why it would be throwing that.

**Comment by JohnPostlethwait** [comment]
I have also never attempted to use this with the package.json, so I have no idea what might happen if you do so...

**Comment by JohnPostlethwait** [comment]
Any luck?

**Comment by konsumer** [comment]
Nope. I switched to [brfs](https://github.com/substack/brfs) because it fit better with my workflow and doesn't require invalid server-side code. Thanks for looking into it!

**Comment by JohnPostlethwait** [comment]
Sorry it didn't work out, glad you found a solution!

**Comment by anshulguleria** [comment]
@konsumer The transform you are providing is wrong.
It would have been correct if you were not passing options to your transform.
Transform is an array of array values when need to pass options to the transform you are using, thus the correct one would be this:
```js
"transform": [
    [
        "stringify", {
            "extensions": ".svg"
        }
    ]
]
```
For more info on the same as written in browserify documentation, read [module-deps](https://github.com/substack/module-deps#packagejson-transformkey). The third example matches your case.
