### ISSUE TITLE
Can't get it to work (ParseError: Unexpected token)

### ISSUE THREAD

**Issue by mparpaillon** [JohnPostlethwait/stringify#16]
Hi,

Your lib is exactly what I was looking for but sadly, I can't get it to work.

I think that Browserify is trying to parse my .hbs files like a js file so I get a "ParseError: Unexpected token".

I use it via a node task which does the following:

```
var entryPath = 'MY_ENTRY_PATH';
var bundlePath = 'MY_BUNDLE_PATH';

browserify({
    debug: true,
})
.transform(stringify({
    extensions: [ '.hbs' ],
    minify: true
}))
.add(entryPath)
.bundle(function(err) {
    if (!err) {
        console.log('File has been saved.');
    }
})
// Write the stream in a real file
.pipe(fs.createWriteStream(bundlePath));
```

Am I doing something wrong ?
Thanks a lot

**Comment by mparpaillon** [comment]
Ok I've managed to make it work but I had to add a global: true as a transform option.

```
...

.transform(stringify({
    extensions: [ '.hbs' ],
    minify: true
}), {
    global: true
})

...

**Comment by JohnPostlethwait** [comment]
That's interesting... I'm nearly positive I've not had to do that, I wonder if this is a versioning issue? Do the tests in this repository pass for you by-chance?

**Comment by mparpaillon** [comment]
I think this issue came from my project tree.
I'm working with private npm packages which I require from my app main.js

So the .hbs files were not found because they were in the node_modules directory (I guess)
Setting the global flag to true fixed it

**Comment by JohnPostlethwait** [comment]
Oh! That makes a lot of sense, and would definitely do it... Thanks for posting about it, this will be here now if anyone else has a similar issue!

**Comment by mykhas** [comment]
Seems like API was changed, now helps: 
```
    .transform(stringify, {
            appliesTo: { extensions: ['.html'] },
            minify: true,
            global: true
        })
```

**Comment by chaddjohnson** [comment]
Just want to say thank you @mparpaillon and @mykhas for mentioning the `global` flag and its usage. I have an NPM package I'm pulling in that uses require-globify and stringify, and things just wouldn't build due to an "Unexpected token" error. Now things work.
