### ISSUE TITLE
Doesn't work with backticks?

### ISSUE THREAD

**Issue by e-monson** [JohnPostlethwait/stringify#20]
I'm trying to use this with gulp to require markdown files as strings, but I'm getting this sort of error:
 
(function (exports, require, module, __filename, __dirname) { ```foo bar baz
                                                                                                 ^
SyntaxError: Unexpected token ILLEGAL

**Comment by e-monson** [comment]
Sorry, but I can't even get the error to display correctly as a code block due to the presence of the backticks.

**Comment by JohnPostlethwait** [comment]
Can you attack the offending Markdown file? That or, if the content is private, make an example file for me that successfully breaks Stringify so I can use it for testing a fix?

**Comment by e-monson** [comment]
[This](https://raw.githubusercontent.com/e-monson/misc-files/master/example.md) should work.

**Comment by JohnPostlethwait** [comment]
Thank you! I will try and get a fix up for you this weekend...

**Comment by e-monson** [comment]
Hey, did you get a chance to look at this? I can try to help, as well.

**Comment by JohnPostlethwait** [comment]
Sorry, no, I haven't yet. :disappointed:  

The two main things that happen are that I use NodeJS' `JSON.stringify` on the string, which I imagine isn't the issue, and it also uses the NPM [HTML Minifier](https://www.npmjs.com/package/html-minifier), which I am suspect of in this error... I haven't looked yet though – sorry about that!

**Comment by e-monson** [comment]
It turns out that my issue wasn't stringify's fault at all. I have an isomorphic app, and I wasn't thinking about what was happening server-side. I got the error because it was trying to 'require' the files normally there.

**Comment by JohnPostlethwait** [comment]
Ah, that makes sense! Thanks for looking into it and closing it out! Sorry for the crappy turn-around time on my part!
