### ISSUE TITLE
relatives directories??

### ISSUE THREAD

**Issue by charlitos85** [JohnPostlethwait/stringify#22]
i use stringify for compile templates very well, but in the compiled file, browserify save the relatives directories with the name, who can change that?

for example:
template: require('../../../template.users.view.html')

browserify generate the colection like this
{"../../../../template.users.view.html":118}

who can remove the './././'???

**Comment by JohnPostlethwait** [comment]
That's just how Browserify works. It sounds like you may be using it in an unsupported manner if you don't want it like that.
