### ISSUE TITLE
Error: Cannot find module './htmlparser'

### ISSUE THREAD

**Issue by fkroockmann** [JohnPostlethwait/stringify#25]
Hello,

I have an error when i watchify:

Error: Cannot find module './htmlparser' from '/home/projects/cloud/node_modules/stringify/node_modules/html-minifier/dist'

Have you got an idea ?

**Comment by fkroockmann** [comment]
Html minifer use require the htmlparser here https://github.com/kangax/html-minifier/blob/gh-pages/dist/htmlminifier.js#L587

But not found in the same dist directory... :/

**Comment by JohnPostlethwait** [comment]
Does this happen only when using stringify?

**Comment by fkroockmann** [comment]
i just use stringify but this bug happen when i use with task runner like gulp. But with command like "-t stringify" that works

**Comment by JohnPostlethwait** [comment]
Can you verify that `/home/projects/cloud/node_modules/stringify/node_modules/html-minifier/dist/htmlparser` isn't actually there?

**Comment by fkroockmann** [comment]
Yes he is not here

**Comment by fkroockmann** [comment]
You can check in htmlminifier repository

**Comment by JohnPostlethwait** [comment]
I'm not clear how you are getting this error. Does this error only happen when using watchify?

**Comment by fkroockmann** [comment]
It's when i use it in task

**Comment by YerkoPalma** [comment]
I'm having this issue too. I'm not using gulp for this task, I'm using stringify with other browserify transform (Vueify) and I get this error. Tell me if you need any more information

**Comment by JohnPostlethwait** [comment]
I need exact reproduction steps or a pointer to a failing app source from someone for me to look at it. I am not clear how to reproduce this.

**Comment by YerkoPalma** [comment]
well, this is my `package.json` file.

    {
      "name": "yerko.personalwebsite",
      "version": "1.0.0",
      "description": "",
      "main": "js/app.js",
      "dependencies": {
        "babel-plugin-transform-runtime": "^6.1.18",
        "babel-preset-es2015": "^6.1.18",
        "babel-runtime": "^6.2.0",
        "chart.js": "^1.0.2",
        "marked": "^0.3.5",
        "vue": "^1.0.8",
        "vue-hot-reload-api": "^1.2.1",
        "vueify": "^6.0.0",
        "vueify-insert-css": "^1.0.0"
      },
      "devDependencies": {
        "brfs": "^1.4.2",
        "browserify-fs": "^1.0.0",
        "gulp": "^3.9.0",
        "gulp-browserify": "^0.5.1",
        "gulp-connect": "^2.2.0",
        "gulp-less": "^3.0.5",
        "gulp-load-plugins": "^1.1.0",
        "gulp-plumber": "^1.0.1",
        "partialify": "^3.1.5",
        "stringify": "^3.2.0"
      },
      "scripts": {
        "build": "browserify -t vueify -e src/app.js -o dist/app.production.js",
        "compile": "browserify -t stringify -t vueify -e src/app.js -o dist/app.production.js"
      },
      "repository": {
         "type": "git",
         "url": "git+https://github.com/YerkoPalma/YerkoPalma.github.io.git"
      },
      "author": "@YerkoPalma",
      "license": "ISC",
      "bugs": {
        "url": "https://github.com/YerkoPalma/YerkoPalma.github.io/issues"
      },
      "homepage": "https://github.com/YerkoPalma/YerkoPalma.github.io#readme"
    }

I use `npm run compile` to compile my app. The app breaks as soon as I add `var stringify = require('stringify')` so the code it isn't important I think.  

Anyway, this is the part of my code that concern to stringify

    var stringify = require('stringify');

    stringify.registerWithRequire({
      extensions: ['.md'],
      minify: false
    });

    var myTextFile = require('./path/to/my/text/file.md');

**Comment by JohnPostlethwait** [comment]
It looks like you are both running it from the command line: ```"compile": "browserify -t stringify -t vueify -e src/app.js -o dist/app.production.js"``` and also running it as a runtime dependency in the source (via your last example)?

Stringify cannot be required as a runtime dependency. It has to be used as a Browserify transform at compile time (and likely using a a build tool like grunt, gulp, etc...) Command-line works, sort of, but you are not yet able to use any options except for the default options that Stringify has.

**Comment by JohnPostlethwait** [comment]
I see the confusion, my first example shows almost exactly what you wrote in your runtime code. This example is a better one of how to use it: https://github.com/JohnPostlethwait/stringify#more-realistic-example--use-case

**Comment by YerkoPalma** [comment]
So, the way to go is to remove `stringify` from the compile command, and add it programatically like the example you posted? I just have one doubt about that example, where did the `app` var came from?

**Comment by JohnPostlethwait** [comment]
To get what you want you can either remove the command line useage from your code, and use a build tool like gulp to browserify/compile everything (and stringify would be required into your build script for gulp to use with browserify). Or you can keep the command-line and remove all references to stringify from your code. The problem with using command-line is that Stringify doesn't currently allow you to set any options from the command-line, so its value is limited to the default options, which I doubt is what you want.

Stringify should never be required into any Javascript file that is part of your Browser if bundle (Browserify should never end up requiring it), which is what is happening in your case.

Conversely you can give me a few days to add better support for the command-line usage so that you will be able to specify Stringify options from the command-line...
