### ISSUE TITLE
Stringify from node_modules not working

### ISSUE THREAD

**Issue by gbates91** [JohnPostlethwait/stringify#27]
If node_modules/abc/file.txt contains the string "123" and I require('abc/file.txt') stringify will create a block  like this in the browserify output: 

13:[function(require,module,exports){
123
},{}]

instead of something like this:

13:[function(require,module,exports){
module.exports = "123"
},{}]

**Comment by JohnPostlethwait** [comment]
It shouldn't matter if it is in node_modules or not. Does this reproduce when requiring a file that is not in node_modules?

What does your stringify configuration look like?

**Comment by gbates91** [comment]
When requiring using relative paths like ../templates/file.txt there is no error. I am using the default stringify configuration.

**Comment by gbates91** [comment]
Looks like it was a design decision for browserify to not apply transforms to files within node_modules: https://github.com/substack/node-browserify/issues/515

I was able to apply the stringify transform globally via:

.transform({global: true}, stringify())

**Comment by JohnPostlethwait** [comment]
Thank you for updating me! I have been curious if it was indeed something else doing the transform improperly...

As an aside, I do think I agree with that design decision in that I have only ever ran into maintenance trouble with doing explicit file-requires from node_modules...

**Comment by throrin19** [comment]
With or without `{ global : true }`, stringify ignore the node_module `.html, .txt, ...` files
