### ISSUE TITLE
String is not correctly reconstructed when it uses quotes

### ISSUE THREAD

**Issue by pschuegr** [JohnPostlethwait/stringify#33]
If you process a text file which includes both single and double quotes, the result of running through the stringify/require process has escaped quotes in it.

Input:
````<div attrib="something containing 'quotes'">````

Output
````<div attrib="something containing \'quotes\'">````

I can see why this happens, but any suggestions on how to fix?  Thanks!

**Comment by JohnPostlethwait** [comment]
What is broken about it?

It needs to escape those quotes because, in the end, it is just a JavaScript string. It shouldn't be affecting the string once JS parses it...

**Comment by pschuegr** [comment]
I see what you're saying, but if my goal is to use stringify to require() text files inside of client-side JavaScript files, I'm not really getting my text file imported as it is.  I'm getting the text file as it is after being converted into a JS string.  It's a very small difference but potentially significant.

**Comment by pschuegr** [comment]
My apologies - I completely misunderstood what was going on here - my source has the escape backslashes in it.

**Comment by JohnPostlethwait** [comment]
No problem! Glad it was figured out! :)
