### ISSUE TITLE
4.0.0 does not work from command line

### ISSUE THREAD

**Issue by wjohnsto** [JohnPostlethwait/stringify#36]
I have a simple js file `in.js`:

```
require('./in.html');
```

and `in.html`:

```
<h1>Hello World!</h1>
```

When I run `browserify in.js -d -t stringify -o out.js` I get the following error:

```
<h1>Hello World!</h1>
^
ParseError: Unexpected token
```

This has something to do with the new Stream2 stuff, since stringify@3.2.1 works just fine. I've tested this with browserify@11.0.0 - 13.0.0 with no success.

**Comment by JohnPostlethwait** [comment]
Sorry about that - it appears I messed up when doing the new stream stuff. This fixes it: https://github.com/JohnPostlethwait/stringify/pull/34

**Comment by JohnPostlethwait** [comment]
I won't be able to publish to NPM for a while, but will put up the fixed version in 8-10 hours.

**Comment by wjohnsto** [comment]
NBD man! Just wanted to make sure you are aware of it. Since 3.2.1 works I'll use that in the mean time.

**Comment by vonKristoff** [comment]
Has this ever been fixed?! I get the same error ..V4.0.0

`browserify -t [ stringify --extensions [.html] ] js/main.js -o public/js/bundle.js`

**Comment by alexeyraspopov** [comment]
Can we bump version in NPM so this fix will be available for users? Thanks

**Comment by JohnPostlethwait** [comment]
Sorry all - been busy with work. It is now up as version 4.0.1, and 4.0.0 is unpublished (as it was totally broken) https://www.npmjs.com/package/stringify

**Comment by wjohnsto** [comment]
Great work! Thanks @JohnPostlethwait
