### ISSUE TITLE
Should this Browserify plugin use "browserify-transform-tools"

### ISSUE THREAD

**Issue by matthewdunsdon** [JohnPostlethwait/stringify#37]
I have been exploring several Browserify plugin and have noticed many plugins make use of the https://github.com/benbria/browserify-transform-tools utilities.

Should we consider cleaning up some of the "through2" code and use of browserify-transform-tools?

**Comment by matthewdunsdon** [comment]
Additional note: If we think this is worth doing, I would be willing to make the changes.

**Comment by JohnPostlethwait** [comment]
I think that makes a lot of sense! Sorry I have been slow (and broken) about updating Stringify – I have admittedly not been doing NodeJS work for the past year+. A PR for this would be awesome!

**Comment by matthewdunsdon** [comment]
I'll start looking into this.  Hopefully I can have something to show by the end of the week.

**Comment by matthewdunsdon** [comment]
Stepping back and looking at the PR, it has cleaned up some of the code using through2.  

The main negative of "browserify-transform-tools" is that is is fairly prescriptive with how the user specifies what files they want to include / exclude. As indicated in the documentation change, the preference is to use `` appliesTo: { includeExtensions: ['.html', '.foo'] }`` instead of ``extensions: ['.html', '.foo']``.  As a result I had to create a ``function getTransformOptions (options) {`` to transform the options object.

The main advantages of the change to use "browserify-transform-tools" would be:

* Stringify could look at the users <kbd>package.json</kbd> file to determine configuration settings. (_see <kbd>README.md</kbd> changes_).
* Stringify allows users to use __appliesTo__ to do more complex file inclusion or exclusion rules.
* If a little more work is done Stringify could hand over file inclusion and exclusion logic for minification over to "browserify-transform-tools" as well, allowing more code to be cleaned up.

| appliesTo option           | Description                   |
| ----------------------------- | ----------------------------- |
| <kbd>.includeExtensions</kbd> | If this option is specified, then any file with an extension not in this list will skipped.  |
| <kbd>.excludeExtensions</kbd> | A list of extensions which will be skipped.  |
| <kbd>.files</kbd>             | A list of paths, relative to the configuration file, of files which should be transformed.  Only these files will be transformed. |
| <kbd>.regex</kbd>             | A regex or a list of regexes.  If any regex matches the full path of the file, then the file will be processed, otherwise not.  |


Anyways @JohnPostlethwait , I will be interested to hear your thoughts on this PR.

**Comment by JohnPostlethwait** [comment]
Sorry for not getting to this sooner – I'll try and look it over as soon as I can.

**Comment by JohnPostlethwait** [comment]
This looks, and works, great! Thanks Matthew!

I will merge it now and do a major version rev in NPM.

**Comment by JohnPostlethwait** [comment]
Version 5.0.0 is up on NPM - thank you so much! https://www.npmjs.com/package/stringify
