### ISSUE TITLE
Update README to be clearer for usage with NPM Scripts.

### ISSUE THREAD

**Issue by liorwohl** [JohnPostlethwait/stringify#40]
I changed from gulp to npm-scripts and now --conservativeCollapse option don't work anymore
(maybe the stringify version updated in the process)

This is the command i'm using (in windows) : 

browserify --no-bundle-external --transform browserify-ngannotate --transform [ stringify --extensions [.html] --minify [ --collapseWhitespace --preserveLineBreaks --conservativeCollapse --removeComments --removeAttributeQuotes --removeTagWhitespace ] ] --debug --plugin [ minifyify --map app.min.js.map --output app.min.js.map ] app.js --outfile app.min.js

Is it stringify bug or something wrong in my command syntax?

thanks

**Comment by JohnPostlethwait** [comment]
Can you verify which version of Stringify you were using when it worked, and which version you are now using?

**Comment by liorwohl** [comment]
Right now i use version 4.0.1, before that i had 3.2.1.
But I just downgraded to 3.2.1 and used it in my npm script, and I still having this bug,
so conservativeCollapse only works when using it in Gulp, not when using in npm script.

**Comment by matthewdunsdon** [comment]
@liorwohl , I wonder if there is something wrong with the command syntax.  The minify options should be in ``{ ..., minifier: { options: { ... } }``.

Could you try using the command:

browserify --no-bundle-external --transform browserify-ngannotate --transform [ stringify --extensions [.html] --minify --minifier [ --options [ --collapseWhitespace --preserveLineBreaks --conservativeCollapse --removeComments --removeAttributeQuotes --removeTagWhitespace ] ] ] --debug --plugin [ minifyify --map app.min.js.map --output app.min.js.map ] app.js --outfile app.min.js

**Comment by liorwohl** [comment]
thanks, that was the problem :)

I think that it needs to be written somewhere more noticeable now that people start using npm scripts more.

**Comment by JohnPostlethwait** [comment]
I agree! Thanks for the feedback! I'll update the README for clarity on this.

**Comment by matthieusieben** [comment]
Note that you can also use `--minifyOptions` as in:
`-t [ stringify --minify --minifyOptions [ --customAttrCollapse /ng-class/ ] --extensions [ .html ] ]`
