### ISSUE TITLE
I'd like require to import html files as template strings

### ISSUE THREAD

**Issue by diffalot** [JohnPostlethwait/stringify#45]
it think it would be really cool to be able to do something like

`template.html`
```html
<h1>Stringify is ${word}</h1>
```

and then in javascript:
```javascript
var word = 'Awesome'
$('body').html(require('template.html'))
```

Has anyone figured out how to do this yet?

**Comment by JohnPostlethwait** [comment]
Hello,

That's kind of outside of the scope of what stringify is meant to do.

What you are looking to do is specifically the job of a template library, like Handlebars, which stringify is meant to compliment, not replace...

**Comment by diffalot** [comment]
yeah, it looks like i've run into the common misconception that template strings _can_ do what a templating library like handlebars does: https://esdiscuss.org/topic/converting-strings-to-template-strings#content-10

Thank you for the great library! I learned a good bit by diving into the souce.

**Comment by JohnPostlethwait** [comment]
Of course! Glad it was helpful - sorry for the misconception!
