### ISSUE TITLE
Usage via grunt

### ISSUE THREAD

**Issue by Pfeifenjoy** [JohnPostlethwait/stringify#46]
Hello,

I am sorry to open this as an issue, but I didn't find a forum where this could be posted.
I would like to include stringify in my grunt task.
Is there any way to do that?

Thanks in advance

**Comment by JohnPostlethwait** [comment]
Not as far as I know, I don't have a Gruntfile for this project.

I'd be down for someone to write one and put up a Pull Request, but I probably won't be doing it myself as it has been years since I have used Grunt...

**Comment by pat-flew** [comment]
Something like this worked for me:

```
browserify: {
	dev: {
		options: {
			transform: [
				[
					'stringify', {
						appliesTo: { includeExtensions: ['.html'] }
					} 
				]
			]
		}
	}
}
```

The stringify transform entry had to precede other transforms.

**Comment by JohnPostlethwait** [comment]
Thanks for posting that @pat-flew!
