### ISSUE TITLE
Update html-minifier to v1.5.0 (at least)

### ISSUE THREAD

**Issue by dackmin** [JohnPostlethwait/stringify#50]
NodeSecurity recently started to yell that `stringify` has a low level vulnerability because it uses `html-minifier`, which depends on `cli#v0.11.x` (responsible for the flaw).

This minor security flaw has been patched in `cli#v1.x.x`. However, `html-minifier` doesn't use `cli` anymore starting with `v1.5.0`.

Is it possible to update `html-minifier` to at least `v1.5.0`, and if it doesn't break anything, to `v3.5.2` ?

Cheers !

**Comment by dackmin** [comment]
Oh, just saw the note from the README file, will try to make a PR 😄

**Comment by JohnPostlethwait** [comment]
Fixed with PR https://github.com/JohnPostlethwait/stringify/pull/51
Published to NPM today as Stringify version 5.2.0.
