### ISSUE TITLE
Cannot use it with browserify -t flag

### ISSUE THREAD

**Issue by mr-mig** [JohnPostlethwait/stringify#8]
Please, see this for details: https://github.com/substack/node-browserify/issues/823

**Comment by skovhus** [comment]
@JohnPostlethwait I've added a pull request solving this #13

**Comment by JohnPostlethwait** [comment]
Awesome, thanks @skovhus – hopefully I can look it over/try it out sometime today!

**Comment by skovhus** [comment]
@JohnPostlethwait Great. Let me know if there is anything... : )

**Comment by JohnPostlethwait** [comment]
With was added with PR #13 landing, it is now published on NPM as version 3.1.0: https://www.npmjs.com/package/stringify

Thanks again for doing this Kenneth!
